/usr/lib64/qt-3.3/bin:/home/allbery/.local/bin:/home/allbery/.cargo/bin:/usr/local/bin:/usr/bin:/usr/games
_JAVA_AWT_WM_NONREPARENTING=1  
GDK_SCALE=1.5
QT_QPA_PLATFORMTHEME=qt5ct
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_ENABLE_HIGHDPI_SCALING=1
